apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: f04954ba-ad1b-4781-ac03-4a93c660918f
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.47.2
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m