spring:
  config:
    import: file:./.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIADB_HOST}/${MARIADB_DATABASE}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASS}

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: "/api/actuator"
      exposure:
        include:
          - info
          - health
          - prometheus

springdoc:
  api-docs:
    path: "/api/docs"
  swagger-ui:
    path: "/api/swagger-ui.html"
