name: Build with Gradle

on:
  push:
    branches: [ "dev", "feature/*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Start Docker containers
        run: docker-compose -f "compose.yaml" up -d --build

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build

      - name: Stop Docker containers
        if: always()
        run: docker-compose -f "compose.yaml" down